version: "1.0"

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - api
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - api
networks:
  api:
    driver: bridge
